# Generated by Django 3.2.18 on 2023-03-10 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_remove_challenge_criteria'),
        ('criteria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterion',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge', to='challenges.challenge'),
        ),
    ]
