# Generated by Django 3.2.18 on 2023-03-13 13:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenges', '0003_remove_challenge_criteria'),
        ('criteria', '0002_alter_criterion_challenge'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Criterion',
            new_name='Criteria',
        ),
    ]
