# Generated by Django 3.2.18 on 2023-03-09 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0012_group_challenge_title'),
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('challenge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='challenges.challenge')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Uploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissionuploads', to='submissions.submission')),
            ],
        ),
    ]
