# Generated by Django 3.2.18 on 2023-03-10 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Uploads',
        ),
    ]
