# Generated by Django 3.2.18 on 2023-03-14 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_submission_stauts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='stauts',
            new_name='status',
        ),
    ]
