# Generated by Django 3.2.18 on 2023-03-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='date',
            field=models.DateField(),
        ),
    ]
