# Generated by Django 3.2.18 on 2023-03-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_group_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='category',
            field=models.CharField(choices=[('SPI', 'Spiritual'), ('FIN', 'Financial'), ('CAR', 'Career'), ('INT', 'Intellectual'), ('FIT', 'Fitness'), ('SOC', 'Social')], max_length=25),
        ),
        migrations.AlterField(
            model_name='group',
            name='repetition',
            field=models.CharField(choices=[('never', 'One Time Challenge'), ('daily', 'Repeats Daily'), ('weekly', 'Repeats Weekly'), ('monthly', 'Repeats Monthly'), ('annualy', 'Repeats Annualy')], default='never', max_length=25),
        ),
    ]
