# Generated by Django 3.2.18 on 2023-03-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20230308_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='criteria',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
