# Generated by Django 3.2.18 on 2023-03-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_auto_20230309_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='criteria',
            field=models.TextField(default='...', max_length=500),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(default='...', max_length=500),
        ),
    ]
