# Generated by Django 3.2.18 on 2023-03-09 09:12

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('groups', '0007_alter_group_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
