# Generated by Django 3.2.18 on 2023-03-09 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0009_alter_group_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
