# Generated by Django 3.2.18 on 2023-03-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0011_group_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='challenge_title',
            field=models.CharField(default='Challenge', max_length=160),
        ),
    ]
