# Generated by Django 3.2.18 on 2023-03-10 04:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='number',
        ),
        migrations.AddField(
            model_name='challenge',
            name='criteria',
            field=models.TextField(default='...', max_length=500),
        ),
        migrations.AddField(
            model_name='challenge',
            name='description',
            field=models.TextField(default='...', max_length=500),
        ),
        migrations.AddField(
            model_name='challenge',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='repetition',
            field=models.CharField(choices=[('never', 'One Time Challenge'), ('daily', 'Repeats Daily'), ('weekly', 'Repeats Weekly'), ('monthly', 'Repeats Monthly'), ('annualy', 'Repeats Annualy')], default='weekly', max_length=25),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='title',
            field=models.CharField(default='Challenge', max_length=160),
        ),
    ]
