# Generated by Django 3.2.18 on 2023-03-10 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_auto_20230310_0437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='criteria',
        ),
    ]
